-- 코드를 작성해주세요
SELECT S.YEAR, S.MAX_SIZE - F.SIZE_OF_COLONY AS YEAR_DEV, F.ID
FROM ECOLI_DATA F JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
                        FROM ECOLI_DATA
                        GROUP BY YEAR(DIFFERENTIATION_DATE)
                     ) S
ON YEAR(F.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY S.YEAR, YEAR_DEV